package com.bookparser.app.parser

object GenreMapper {

    private val fb2GenreMapping = mapOf(
        "sf_history" to "Альтернативная история",
        "sf_action" to "Боевая фантастика",
        "sf_epic" to "Фантастика",
        "sf_heroic" to "Фантастика",
        "sf_detective" to "Детективная фантастика",
        "sf_cyberpunk" to "Киберпанк/Стимпанк/Паропанк",
        "sf_stimpank" to "Киберпанк/Стимпанк/Паропанк",
        "sf_space" to "Космическая фантастика",
        "sf_social" to "Социально-психологическая фантастика",
        "sf_horror" to "Мистика и ужасы",
        "sf_humor" to "Юмористическая фантастика",
        "sf_fantasy" to "Фэнтези",
        "sf" to "Научная фантастика",
        "sf_realrpg" to "ЛитРПГ/РеалРПГ",
        "sf_litrpg" to "ЛитРПГ/РеалРПГ",
        "sf_postapocalyptic" to "Постапокалипсис",
        "dark_fantasy" to "Фэнтези",
        "fantasy_action" to "Фэнтези",
        "hronoopera" to "Хроноопера",
        "sf_all" to "Фантастика",
        "sf_mystic" to "Мистика и ужасы",
    
        "det_classic" to "Детектив",
        "det_police" to "Детектив",
        "det_action" to "Боевик",
        "det_irony" to "Детектив",
        "det_history" to "История",
        "det_espionage" to "Триллеры",
        "det_crime" to "Криминал",
        "det_political" to "Политика",
        "det_maniac" to "Триллеры",
        "det_hard" to "Детектив",
        "thriller" to "Триллеры",
        "detective" to "Детектив",
        "det_all" to "Детектив",
    
        "popadanec" to "Попаданцы",
        "popadancy" to "Попаданцы",
        "back_to_ussr" to "Назад в СССР",
        "back-to-ussr" to "Назад в СССР",
        "prose_classic" to "Романы и повести",
        "prose_history" to "История",
        "prose_contemporary" to "Романы и повести",
        "prose_counter" to "Контркультура",
        "prose_rus_classic" to "Романы и повести",
        "prose_su_classics" to "Романы и повести",
        "great_story" to "Романы и повести",
        "roman" to "Романы и повести",
    
        "love_contemporary" to "Романы и повести",
        "love_history" to "Романы и повести",
        "love_detective" to "Детектив",
        "love_short" to "Романы и повести",
        "love_erotica" to "Романы и повести",
    
        "adv_western" to "Приключения",
        "adv_history" to "Приключения",
        "adv_indian" to "Приключения",
        "adv_maritime" to "Приключения",
        "adv_geo" to "Путешествия и география",
        "adv_animal" to "Природа и животные",
        "adventure" to "Приключения",
        "adv_all" to "Приключения",
    
        "child_tale" to "Сказки, мифы и легенды",
        "child_verse" to "Детская литература",
        "child_prose" to "Детская литература",
        "child_sf" to "Детская литература",
        "child_det" to "Детская литература",
        "child_adv" to "Детская литература",
        "child_education" to "Детская литература",
        "children" to "Детская литература",
        "Child_all" to "Детская литература",
    
        "poetry" to "Поэзия",
        "dramaturgy" to "Драматургия и комедия",
        "poetry_all" to "Поэзия",
    
        "antique_ant" to "История",
        "antique_european" to "История",
        "antique_russian" to "История",
        "antique_east" to "История",
        "antique_myths" to "Сказки, мифы и легенды",
        "antique" to "История",
        "history_all" to "История",
    
        "sci_history" to "История",
        "sci_psychology" to "Психология",
        "sci_culture" to "Культурология",
        "sci_religion" to "Религия и эзотерика",
        "sci_philosophy" to "Философия",
        "sci_politics" to "Политика",
        "sci_business" to "Бизнес литература",
        "sci_juris" to "Юриспруденция",
        "sci_linguistic" to "Языки и словари",
        "sci_medicine" to "Медицина и здоровье",
        "sci_phys" to "Технические науки",
        "sci_math" to "Технические науки",
        "sci_chem" to "Технические науки",
        "sci_biology" to "Наука и образование",
        "sci_tech" to "Технические науки",
        "science" to "Наука и образование",
        "psycho_all" to "Психология",
        "banking_all" to "Бизнес литература",
        "Sci_all" to "Наука и образование",
        "foreign_language" to "Языки и словари",
    
        "comp_www" to "Компьютерная литература",
        "comp_programming" to "Компьютерная литература",
        "comp_hard" to "Компьютерная литература",
        "comp_soft" to "Компьютерная литература",
        "comp_db" to "Компьютерная литература",
        "comp_osnet" to "Компьютерная литература",
        "computers" to "Компьютерная литература",
        "comp_all" to "Компьютерная литература",
    
        "ref_encyc" to "Справочная литература",
        "ref_dict" to "Языки и словари",
        "ref_ref" to "Справочная литература",
        "ref_guide" to "Справочная литература",
        "reference" to "Справочная литература",
        "ref_all" to "Справочная литература",
    
        "nonf_biography" to "Мемуары и биографии",
        "nonf_publicism" to "Публицистика",
        "nonf_criticism" to "Критика",
        "design" to "Хобби и досуг",
        "nonfiction" to "Документальная литература",
        "nonf_all" to "Документальная литература",
        "military_memoirs" to "Мемуары и биографии",
    
        "religion_rel" to "Религия и эзотерика",
        "religion_esoterics" to "Религия и эзотерика",
        "religion_self" to "Психология",
        "religion" to "Религия и эзотерика",
        "rel_all" to "Религия и эзотерика",
    
        "humor_anecdote" to "Юмор",
        "humor_prose" to "Юмор",
        "humor_verse" to "Юмор",
        "humor" to "Юмор",
        "humor_all" to "Юмор",
    
        "home_cooking" to "Кулинария",
        "home_pets" to "Домашние животные",
        "home_crafts" to "Хобби и досуг",
        "home_entertain" to "Хобби и досуг",
        "home_health" to "Медицина и здоровье",
        "home_garden" to "Сад и огород",
        "home_diy" to "Сделай сам",
        "home_sport" to "Спорт",
        "home_sex" to "Романы и повести",
        "home" to "Хобби и досуг",
        "home_all" to "Дом и семья",
        "hobbies_all" to "Хобби и досуг",
    
        "periodic" to "Журналы и комиксы",
        "military" to "О войне",
        "nonf_military" to "О войне",
        "military_history" to "О войне",
        "poetry_military" to "О войне"
    )
    
    fun mapFb2GenresToPda(fb2Genres: List<String>): Set<String> {
        val mapped = mutableSetOf<String>()
        for (genre in fb2Genres) {
            fb2GenreMapping[genre]?.let { mapped.add(it) }
        }
        return mapped
    }
}
